version: "3"
services:
  fs-intake-postgres:
    image: postgres:9.6.3
    ports:
      - "5433:5432"
    networks:
      - fs-intake
    environment:
      POSTGRES_PASSWORD: postgres
  fs-intake-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile-server
    ports:
      - "8080:8080"
    volumes:
      - ../server:/app
      - /app/node_modules
    depends_on:
      - fs-intake-postgres
    networks:
      - fs-intake
    links:
      - fs-intake-postgres
  fs-intake-frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile-frontend
    ports:
      - "4200:4200"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /dev/shm:/dev/shm
    depends_on:
      - fs-intake-server
    networks:
      - fs-intake
    user: root
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - fs-intake-postgres
    networks:
      - fs-intake
    links:
      - fs-intake-postgres
  fs-intake-pa11y:
      build:
        context: ..
        dockerfile: docker/Dockerfile-pa11y
      ports:
        - "4200:4200"
      volumes:
        - ../frontend:/app
        - /app/node_modules
        - /dev/shm:/dev/shm
      depends_on:
        - fs-intake-server
      networks:
        - fs-intake
      user: root
networks:
  fs-intake:
